package org.core.utilidades.util.exception;

public class NumeroFueraDeRangoException extends Exception{
    public NumeroFueraDeRangoException(int rangoMinimo, int rangoMaximo, int numero){
        super("El n√∫mero " + numero + " se encuentra fuera del rango " + " {" + rangoMinimo + ":" + rangoMaximo  + "}.");
    }
}
